architect:
  - yegor256
  - andreoss
assets:
  settings.xml: yegor256/home#assets/jcabi/settings.xml
  secring.gpg: yegor256/home#assets/secring.gpg
  pubring.gpg: yegor256/home#assets/pubring.gpg
install: |
  sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
  pdd --file=/dev/null
merge:
  script: |
    mvn clean install -Pqulice --errors --batch-mode
release:
  pre: false
  script: |-
    mvn versions:set "-DnewVersion=${tag}" --batch-mode
    git commit -am "${tag}"
    mvn clean deploy -Pqulice -Psonatype -Pjcabi --batch-mode --errors --settings ../settings.xml
    mvn clean site-deploy -Psite --errors --settings ../settings.xml --batch-mode