# SPDX-FileCopyrightText: Copyright (c) 2011-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: OWASP
'on':
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    branches:
      - master


jobs:
  owasp:
    timeout-minutes: 45
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
      - name: Maven
        run: |
            if [ -z "${NVD_API_KEY:-}" ]; then
                echo "NVD_API_KEY is NOT set"
                exit 1
            else
                mvn -DnvdApiKey="$NVD_API_KEY" --errors --batch-mode -Powasp dependency-check:check
            fi
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
