name: OWASP
on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
    branches: [ master ]


jobs:
  owasp:
    name: Dependency-Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Maven
        run:  mvn --errors --batch-mode -Powasp dependency-check:check
